server:
  port: 8084

spring:
  data:
    mongodb:
      uri: mongodb+srv://manuelcarrascal:aydTJGm0XP5p40CJ@plazoleta.ly5cgey.mongodb.net/traceability
      auto-index-creation: true
  cloud:
    config:
      enabled: false
appDescription: "Pragma Powerup"
appVersion: "1.0.0"
